inherit_gem:
  rubocop-espago: sorbet.yml

AllCops:
  TargetRubyVersion: 3.4

Metrics/PerceivedComplexity:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/YodaExpression:
  Enabled: false

Sorbet/ForbidTTypeAlias:
  Enabled: false

Sorbet/CallbackConditionalsBinding:
  Enabled: false

Style/InvertibleUnlessCondition:
  Enabled: false

Style/GuardClause:
  Enabled: false

Sorbet/ForbidMixesInClassMethods:
  Enabled: false

Lint/SafeNavigationConsistency:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/SafeNavigationChainLength:
  Enabled: false

Lint/SelfAssignment:
  Enabled: false

Sorbet/RedundantExtendTSig:
  Enabled: false

Style/HashLookupMethod:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/InfiniteLoop:
  Enabled: false

Sorbet/ForbidTUnsafe:
  Enabled: false

Sorbet/ForbidTSig:
  Enabled: false

Lint/BooleanSymbol:
  Enabled: false

Sorbet/ForbidTypeAliasedShapes:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/OneClassPerFile:
  Enabled: false

Sorbet/ForbidTHelpers:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/ItBlockParameter:
  Enabled: false
