AllCops:
  TargetRubyVersion: 3.2

inherit_gem:
  rubocop-espago: sorbet.yml

Lint/BooleanSymbol:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/YodaExpression:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Lint/DeprecatedConstants:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/InfiniteLoop:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Layout/EmptyLinesAroundArguments:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Sorbet/RedundantExtendTSig:
  Enabled: false

Sorbet/ForbidTUnsafe:
  Enabled: false

Sorbet/ForbidTypeAliasedShapes:
  Enabled: false

Sorbet/ForbidTUntyped:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Lint/RedundantRequireStatement:
  Enabled: false
